from haystack.forms import FacetedSearchForm as BaseFacetedSearchForm
from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView


class FacetedSearchForm(BaseFacetedSearchForm):
    def no_query_found(self):
        return self.searchqueryset.auto_query('')


class FacetedSearchView(BaseFacetedSearchView):
    form_class = FacetedSearchForm
    # List of facets on relationship objects
    facet_fields = [
        'observer_name_sort',
        'rt_q',
        'rt_q_x',
        'rt_q_monnayage',
        'rt_tm',
        'rt_tm_snd',
        'rt_tm_minv',
        'rt_tm_retrograde',
        'rt_tm_ms',
        'rt_tm_transposed',
        'rt_tm_invertible',
        'rt_tnm',
        'rt_tnm_embellished',
        'rt_tnm_reduced',
        'rt_tnm_amplified',
        'rt_tnm_truncated',
        'rt_tnm_ncs',
        'rt_tnm_ocs',
        'rt_tnm_ocst',
        'rt_tnm_nc',
        'rt_nm',
        'rt_om',
        'model_observer_name_sort',
        'model_mt_cf',
        'model_mt_cf_dur',
        'model_mt_cf_mel',
        'model_mt_sog',
        'model_mt_sog_dur',
        'model_mt_sog_mel',
        'model_mt_sog_ostinato',
        'model_mt_sog_periodic',
        'model_mt_csog',
        'model_mt_csog_dur',
        'model_mt_csog_mel',
        'model_mt_cd',
        'model_mt_fg',
        'model_mt_fg_periodic',
        'model_mt_fg_strict',
        'model_mt_fg_flexed',
        'model_mt_fg_sequential',
        'model_mt_fg_inverted',
        'model_mt_fg_retrograde',
        'model_mt_id',
        'model_mt_id_strict',
        'model_mt_id_flexed',
        'model_mt_id_flt',
        'model_mt_id_invertible',
        'model_mt_pe',
        'model_mt_pe_strict',
        'model_mt_pe_flexed',
        'model_mt_pe_flt',
        'model_mt_pe_sequential',
        'model_mt_pe_added',
        'model_mt_pe_invertible',
        'model_mt_nid',
        'model_mt_nid_strict',
        'model_mt_nid_flexed',
        'model_mt_nid_flt',
        'model_mt_nid_sequential',
        'model_mt_nid_invertible',
        'model_mt_hr',
        'model_mt_hr_simple',
        'model_mt_hr_staggered',
        'model_mt_hr_sequential',
        'model_mt_hr_fauxbourdon',
        'model_mt_cad',
        'model_mt_cad_authentic',
        'model_mt_cad_phrygian',
        'model_mt_cad_plagal',
        'model_mt_int',
        'model_mt_int_p6',
        'model_mt_int_p3',
        'model_mt_int_c35',
        'model_mt_int_c83',
        'model_mt_int_c65',
        'model_mt_fp',
        'model_mt_fp_ir',
        'model_composer',
        'model_genre',
        'model_date',
        'derivative_observer_name_sort',
        'derivative_mt_cf',
        'derivative_mt_cf_dur',
        'derivative_mt_cf_mel',
        'derivative_mt_sog',
        'derivative_mt_sog_dur',
        'derivative_mt_sog_mel',
        'derivative_mt_sog_ostinato',
        'derivative_mt_sog_periodic',
        'derivative_mt_csog',
        'derivative_mt_csog_dur',
        'derivative_mt_csog_mel',
        'derivative_mt_cd',
        'derivative_mt_fg',
        'derivative_mt_fg_periodic',
        'derivative_mt_fg_strict',
        'derivative_mt_fg_flexed',
        'derivative_mt_fg_sequential',
        'derivative_mt_fg_inverted',
        'derivative_mt_fg_retrograde',
        'derivative_mt_id',
        'derivative_mt_id_strict',
        'derivative_mt_id_flexed',
        'derivative_mt_id_flt',
        'derivative_mt_id_invertible',
        'derivative_mt_pe',
        'derivative_mt_pe_strict',
        'derivative_mt_pe_flexed',
        'derivative_mt_pe_flt',
        'derivative_mt_pe_sequential',
        'derivative_mt_pe_added',
        'derivative_mt_pe_invertible',
        'derivative_mt_nid',
        'derivative_mt_nid_strict',
        'derivative_mt_nid_flexed',
        'derivative_mt_nid_flt',
        'derivative_mt_nid_sequential',
        'derivative_mt_nid_invertible',
        'derivative_mt_hr',
        'derivative_mt_hr_simple',
        'derivative_mt_hr_staggered',
        'derivative_mt_hr_sequential',
        'derivative_mt_hr_fauxbourdon',
        'derivative_mt_cad',
        'derivative_mt_cad_authentic',
        'derivative_mt_cad_phrygian',
        'derivative_mt_cad_plagal',
        'derivative_mt_int',
        'derivative_mt_int_p6',
        'derivative_mt_int_p3',
        'derivative_mt_int_c35',
        'derivative_mt_int_c83',
        'derivative_mt_int_c65',
        'derivative_mt_fp',
        'derivative_mt_fp_ir',
        'derivative_composer',
        'derivative_genre',
        'derivative_date',
    ]

    context_object_name = 'page_object'
