
USERS_TO_KEEP = (9, 10, 11, 12, 13, 14, 16, 18, 20, 22, 23, 24)

PEOPLE = {
    '1': 'CRIM_Person_1021',
    '5': 'CRIM_Person_1022',
    '6': 'CRIM_Person_1023',
    '7': 'CRIM_Person_1004',
    '8': 'CRIM_Person_1005',
    '9': 'CRIM_Person_1006',
    '10': 'CRIM_Person_1003',
    '11': 'CRIM_Person_1008',
    '12': 'CRIM_Person_1009',
    '13': 'CRIM_Person_1010',
    '14': 'CRIM_Person_1011',
    '15': 'CRIM_Person_1012',
    '16': 'CRIM_Person_1013',
    '17': 'CRIM_Person_1014',
    '18': 'CRIM_Person_1015',
    '19': 'CRIM_Person_1016',
    '20': 'CRIM_Person_1017',
    '21': 'CRIM_Person_1018',
    '22': 'CRIM_Person_1007',
    '23': 'CRIM_Person_1019',
    '24': 'CRIM_Person_1020',
    '25': 'CRIM_Person_1024',
}

PIECES = {
    'Sohier. Missa Vidi speciosam (Kyrie)': 'CRIM_Mass_0002_1',
    'Sohier. Missa Vidi speciosam (Gloria)': 'CRIM_Mass_0002_2',
    'Sohier. Missa Vidi speciosam (Credo)': 'CRIM_Mass_0002_3',
    'Sohier. Missa Vidi speciosam (Sanctus)': 'CRIM_Mass_0002_4',
    'Sohier. Missa Vidi speciosam (Agnus)': 'CRIM_Mass_0002_5',
    'Marle. Missa O gente brunette (Kyrie)': 'CRIM_Mass_0003_1',
    'Marle. Missa O gente brunette (Gloria)': 'CRIM_Mass_0003_2',
    'Marle. Missa O gente brunette (Credo)': 'CRIM_Mass_0003_3',
    'Marle. Missa O gente brunette (Sanctus)': 'CRIM_Mass_0003_4',
    'Marle. Missa O gente brunette (Agnus)': 'CRIM_Mass_0003_5',
    'Clereau. Missa Virginis Mariae (Kyrie)': 'CRIM_Mass_0004_1',
    'Févin. Missa Ave Maria (Kyrie)': 'CRIM_Mass_0005_1',
    'Guyon. Missa Je suis déshéritée (Kyrie)': 'CRIM_Mass_0006_1',
    'Gombert. Missa Je suis déshéritée (Kyrie)': 'CRIM_Mass_0007_1',
    'Gombert. Missa Je suis déshéritée (Gloria)': 'CRIM_Mass_0007_2',
    'Sermisy. Missa Quare fremuerunt gentes (Kyrie)': 'CRIM_Mass_0008_1',
    'Sermisy. Missa Quare fremuerunt gentes (Gloria)': 'CRIM_Mass_0008_2',
    'Sermisy, Claudin de: Sermisy. Missa Tota pulchra es (Kyrie)': 'CRIM_Mass_0009_1',
    'Sermisy, Claudin de: Sermisy. Missa Tota pulchra es (Gloria)': 'CRIM_Mass_0009_2',
    'Sermisy, Claudin de: Sermisy. Missa Tota pulchra es (Credo)': 'CRIM_Mass_0009_3',
    'Sermisy, Claudin de: Sermisy. Missa Tota pulchra es (Sanctus)': 'CRIM_Mass_0009_4',
    'Sermisy, Claudin de: Sermisy. Missa Tota pulchra es (Agnus)': 'CRIM_Mass_0009_5',
    'Févin. Missa Mente tota (Kyrie)': 'CRIM_Mass_0014_1',
    'Févin. Missa Mente tota (Gloria)': 'CRIM_Mass_0014_2',
    'Palestrina. Missa Benedicta es (Kyrie)': 'CRIM_Mass_0015_1',
    'Palestrina. Missa Benedicta es (Gloria)': 'CRIM_Mass_0015_2',
    'Palestrina. Missa Benedicta es (Credo)': 'CRIM_Mass_0015_3',
    'Palestrina. Missa Benedicta es (Sanctus)': 'CRIM_Mass_0015_4',
    'Palestrina. Missa Benedicta es (Agnus)': 'CRIM_Mass_0015_5',
    'Forestier, Mathurin: Forestier. Missa Baisés moy ma doulce amye (Kyrie)': 'CRIM_Mass_0017_1',
    'Forestier, Mathurin: Forestier. Missa Baisés moy ma doulce amye (Gloria)': 'CRIM_Mass_0017_2',
    'Forestier, Mathurin: Forestier. Missa Baisés moy ma doulce amye (Credo)': 'CRIM_Mass_0017_3',
    'Forestier, Mathurin: Forestier. Missa Baisés moy ma doulce amye (Sanctus)': 'CRIM_Mass_0017_4',
    'Forestier, Mathurin: Forestier. Missa Baisés moy ma doulce amye (Agnus)': 'CRIM_Mass_0017_5',
    'Palestrina. Missa Veni sponsa Christi (Kyrie)': 'CRIM_Mass_0019_1',
    'Palestrina. Missa Veni sponsa Christi (Gloria)': 'CRIM_Mass_0019_2',
    'Palestrina. Missa Veni sponsa Christi (Credo)': 'CRIM_Mass_0019_3',
    'Palestrina. Missa Veni sponsa Christi (Sanctus)': 'CRIM_Mass_0019_4',
    'Palestrina. Missa Veni sponsa Christi (Agnus)': 'CRIM_Mass_0019_5',
    'Lassus, Roland de: Lassus. Missa Susanne un jour (Kyrie)': 'CRIM_Mass_0020_1',
    'Lassus, Roland de: Lassus. Missa Susanne un jour (Gloria)': 'CRIM_Mass_0020_2',
    'Lassus, Roland de: Lassus. Missa Susanne un jour (Credo)': 'CRIM_Mass_0020_3',
    'Lassus, Roland de: Lassus. Missa Susanne un jour (Sanctus)': 'CRIM_Mass_0020_4',
    'Lassus, Roland de: Lassus. Missa Susanne un jour (Agnus)': 'CRIM_Mass_0020_5',
    'Lupi. Vidi speciosam sicut columbam': 'CRIM_Model_0001',
    'Champion. O gente brunette': 'CRIM_Model_0002',
    'Anonymus. Graduale triplex - Kyrie': 'CRIM_Model_0003',
    'Josquin. Ave Maria': 'CRIM_Model_0008',
    'Cadéac. Je suis déshéritée': 'CRIM_Model_0009',
    'Sermisy. Quare fremuerunt gentes': 'CRIM_Model_0010',
    'Sermisy, Claudin de: Sermisy. Tota pulchra es': 'CRIM_Model_0011',
    'Josquin. Mente Tota': 'CRIM_Model_0016',
    'Josquin. Benedicta es': 'CRIM_Model_0017',
    'Josquin Des Prés: Josquin. Baises moy': 'CRIM_Model_0018',
    'Palestrina. Veni sponsa Christi': 'CRIM_Model_0019',
    'Lassus, Roland de: Lassus. Susanne un jour': 'CRIM_Model_0020',
    'Benedicta es,cælorum Regina': 'CRIM_Model_0021',
    'Benedicta es': 'CRIM_Model_0022',
    'Lupi, Didier: Lupi. Susanne un jour': 'CRIM_Model_0024',
}
