"""
Django settings for crim project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from crim.settings_production import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!si#%r2x)6yu*dlxw#rx#)1w1gm+1jkz+zwr&_w2-ldr*9js%d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '159.65.177.99']


# Application definition

INSTALLED_APPS = [
    'crim',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.flatpages',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'bootstrap_pagination',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crim.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = False

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = False

DATE_FORMAT = 'Y-m-d'
TIME_FORMAT = 'H:m'
DATETIME_FORMAT = 'Y-m-d, H:m'
SHORT_DATETIME_FORMAT = 'Y-m-d, H:m'

USE_TZ = True

LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'

# Make it acceptable for users to leave off a slash in URLs
APPEND_SLASH = True

SITE_ID = 2

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'crim/static')

SOLR_FACET_FIELDS = [
    'observer_s',
    'model_title_s',
    'model_mass_s',
    'model_observer_s',
    'model_composer_s',
    'model_genre_s',
    'derivative_title_s',
    'derivative_mass_s',
    'derivative_observer_s',
    'derivative_composer_s',
    'derivative_genre_s',
    'rt_q_b',
    'rt_q_x_b',
    'rt_q_monnayage_b',
    'rt_tm_b',
    'rt_tm_snd_b',
    'rt_tm_minv_b',
    'rt_tm_retrograde_b',
    'rt_tm_ms_b',
    'rt_tm_transposed_b',
    'rt_tm_invertible_b',
    'rt_tnm_b',
    'rt_tnm_embellished_b',
    'rt_tnm_reduced_b',
    'rt_tnm_amplified_b',
    'rt_tnm_truncated_b',
    'rt_tnm_ncs_b',
    'rt_tnm_ocs_b',
    'rt_tnm_ocst_b',
    'rt_tnm_nc_b',
    'rt_nm_b',
    'rt_om_b',
]
# The mapping between the search form parameters and the
# Solr fields.
SEARCH_PARAM_MAP = {
    'q': 'q',
    'observer': 'observer_s',
    'model-observer': 'model_observer_s',
    'model-composer': 'model_composer_s',
    'model-genre': 'model_genre_s',
    'derivative-observer': 'derivative_observer_s',
    'derivative-composer': 'derivative_composer_s',
    'derivative-genre': 'derivative_genre_s',
    'rt-q': 'rt_q_b',
    'rt-q-exact': 'rt_q_x_b',
    'rt-q-monnayage': 'rt_q_monnayage_b',
    'rt-tm': 'rt_tm_b',
    'rt-tm-snd': 'rt_tm_snd_b',
    'rt-tm-minv': 'rt_tm_minv_b',
    'rt-tm-retrograde': 'rt_tm_retrograde_b',
    'rt-tm-ms': 'rt_tm_ms_b',
    'rt-tm-transposed': 'rt_tm_transposed_b',
    'rt-tm-invertible': 'rt_tm_invertible_b',
    'rt-tnm': 'rt_tnm_b',
    'rt-tnm-embellished': 'rt_tnm_embellished_b',
    'rt-tnm-reduced': 'rt_tnm_reduced_b',
    'rt-tnm-amplified': 'rt_tnm_amplified_b',
    'rt-tnm-truncated': 'rt_tnm_truncated_b',
    'rt-tnm-ncs': 'rt_tnm_ncs_b',
    'rt-tnm-ocs': 'rt_tnm_ocs_b',
    'rt-tnm-ocst': 'rt_tnm_ocst_b',
    'rt-tnm-nc': 'rt_tnm_nc_b',
    'rt-nm': 'rt_nm_b',
    'rt-om': 'rt_om_b',
}
