name: crim_test
on: [push] # activates the workflow on Push
jobs:
  test_crim_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install flake8
      - run: pip install -r dev_requirements.txt # install dependencies from the Deveopment Requirements
      - run: python manage.py makemigrations # making migrations
      - run: python manage.py migrate # migration
      - run: python manage.py loaddata crim/fixtures/definitions.json # importing definitions
      - run: python manage.py test --settings=crim.test_settings # run Python test
      - run: flake8 . # run flake8 test